
FROM ubuntu:16.04
MAINTAINER Mathew Salvaris <mathew.salvaris@microsoft.com>

RUN mkdir /code
WORKDIR /code
ADD . /code/
ADD etc /etc

RUN apt-get update && apt-get install -y  \
        python3 \
        python3-dev \
        python3-setuptools \
        python3-pip &&\
    pip3 install -r /code/requirements.txt

EXPOSE 5000
CMD ["python3", "app.py"]
