replicaCount: 1
image:
  useImagePullSecrets: false
  pullPolicy: Always
service:
  internalPort: 5000
  externalPort: 80
ingress:
  enabled: true
  basedomain: abitest-dns-f4d5b0eb.hcp.southeastasia.azmk8s.io # replace with your own from the portal
